import "./globals.css";
import connectToDatabase from "@/libs/db"; // Asegúrate de que la ruta sea correcta

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

connectToDatabase();

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="antialiased">{children}</body>
    </html>
  );
}
